version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/fastube
permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/clean_directory.sh
      timeout: 6000
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_python_dependencies.sh
      timeout: 6000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 6000
      runas: root
